# Generated by Django 3.2.12 on 2022-12-02 07:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_organization_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=230)),
                ('picture_id_verified', models.CharField(max_length=230)),
                ('test_reason', models.CharField(max_length=230)),
                ('first_name', models.CharField(max_length=230)),
                ('last_name', models.CharField(max_length=230)),
                ('license_no', models.CharField(max_length=230)),
                ('email', models.EmailField(max_length=230)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('product_sku', models.CharField(max_length=230)),
                ('product_name', models.CharField(max_length=230)),
                ('marijuana', models.CharField(max_length=230)),
                ('cocaine', models.CharField(max_length=230)),
                ('image1', models.FileField(null=True, upload_to='media/uploads/')),
                ('image2', models.FileField(null=True, upload_to='media/uploads/')),
                ('specimen', models.CharField(max_length=230)),
                ('signature', models.FileField(null=True, upload_to='media/uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
