# Generated by Django 3.2.12 on 2022-10-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='media/uploads/'),
        ),
    ]
