# Generated by Django 3.2.12 on 2022-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[(1, '1jdfh'), (2, '2sadf'), (3, '3sdf')], max_length=20, null=True),
        ),
    ]
