# Generated by Django 3.2.12 on 2022-11-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20221112_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='product',
            name='Is_Purchasable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Is_Variable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
